--
-- PostgreSQL database dump
--

\restrict 10V82aseLUy9CsdceEd2YqtLbEioqFFHQ3OriqPsVUIbcOedwZzai1XkpoQZyvK

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg12+1)
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-27 19:52:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: retrivo_db_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO retrivo_db_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16411)
-- Name: Categories; Type: TABLE; Schema: public; Owner: retrivo_db_user
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Categories" OWNER TO retrivo_db_user;

--
-- TOC entry 220 (class 1259 OID 16410)
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16463)
-- Name: Claims; Type: TABLE; Schema: public; Owner: retrivo_db_user
--

CREATE TABLE public."Claims" (
    "Id" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "ClaimantName" character varying(100) NOT NULL,
    "ClaimantEmail" character varying(150) NOT NULL,
    "ClaimantPhone" character varying(20),
    "Message" character varying(1000) NOT NULL,
    "PhotoUrl" character varying(500),
    "CreatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Claims" OWNER TO retrivo_db_user;

--
-- TOC entry 226 (class 1259 OID 16462)
-- Name: Claims_Id_seq; Type: SEQUENCE; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE public."Claims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Claims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16434)
-- Name: Items; Type: TABLE; Schema: public; Owner: retrivo_db_user
--

CREATE TABLE public."Items" (
    "Id" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "CategoryId" integer NOT NULL,
    "Location" character varying(200) NOT NULL,
    "PhotoUrl" character varying(500),
    "ItemType" character varying(10) NOT NULL,
    "Status" character varying(20) DEFAULT 'Pending'::character varying NOT NULL,
    "ReporterId" integer NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now(),
    "UpdatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Items" OWNER TO retrivo_db_user;

--
-- TOC entry 224 (class 1259 OID 16433)
-- Name: Items_Id_seq; Type: SEQUENCE; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE public."Items" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Items_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16420)
-- Name: Users; Type: TABLE; Schema: public; Owner: retrivo_db_user
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "Phone" character varying(20),
    "IsAdmin" boolean DEFAULT false,
    "CreatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Users" OWNER TO retrivo_db_user;

--
-- TOC entry 222 (class 1259 OID 16419)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16399)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: retrivo_db_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO retrivo_db_user;

--
-- TOC entry 3258 (class 2606 OID 16418)
-- Name: Categories PK__Categori__3214EC079746DD94; Type: CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK__Categori__3214EC079746DD94" PRIMARY KEY ("Id");


--
-- TOC entry 3271 (class 2606 OID 16475)
-- Name: Claims PK__Claims__3214EC07B38EA2CF; Type: CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Claims"
    ADD CONSTRAINT "PK__Claims__3214EC07B38EA2CF" PRIMARY KEY ("Id");


--
-- TOC entry 3268 (class 2606 OID 16451)
-- Name: Items PK__Items__3214EC07135D681D; Type: CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "PK__Items__3214EC07135D681D" PRIMARY KEY ("Id");


--
-- TOC entry 3261 (class 2606 OID 16432)
-- Name: Users PK__Users__3214EC07A7F39F46; Type: CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK__Users__3214EC07A7F39F46" PRIMARY KEY ("Id");


--
-- TOC entry 3256 (class 2606 OID 16405)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3269 (class 1259 OID 16482)
-- Name: IX_Claims_ItemId; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE INDEX "IX_Claims_ItemId" ON public."Claims" USING btree ("ItemId");


--
-- TOC entry 3263 (class 1259 OID 16483)
-- Name: IX_Items_CategoryId; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE INDEX "IX_Items_CategoryId" ON public."Items" USING btree ("CategoryId");


--
-- TOC entry 3264 (class 1259 OID 16484)
-- Name: IX_Items_ItemType; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE INDEX "IX_Items_ItemType" ON public."Items" USING btree ("ItemType");


--
-- TOC entry 3265 (class 1259 OID 16485)
-- Name: IX_Items_ReporterId; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE INDEX "IX_Items_ReporterId" ON public."Items" USING btree ("ReporterId");


--
-- TOC entry 3266 (class 1259 OID 16486)
-- Name: IX_Items_Status; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE INDEX "IX_Items_Status" ON public."Items" USING btree ("Status");


--
-- TOC entry 3259 (class 1259 OID 16481)
-- Name: UQ__Categori__737584F6E3C1B167; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE UNIQUE INDEX "UQ__Categori__737584F6E3C1B167" ON public."Categories" USING btree ("Name");


--
-- TOC entry 3262 (class 1259 OID 16487)
-- Name: UQ__Users__A9D10534045EB887; Type: INDEX; Schema: public; Owner: retrivo_db_user
--

CREATE UNIQUE INDEX "UQ__Users__A9D10534045EB887" ON public."Users" USING btree ("Email");


--
-- TOC entry 3274 (class 2606 OID 16476)
-- Name: Claims FK_Claims_Items; Type: FK CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Claims"
    ADD CONSTRAINT "FK_Claims_Items" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- TOC entry 3272 (class 2606 OID 16452)
-- Name: Items FK_Items_Categories; Type: FK CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Categories" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id");


--
-- TOC entry 3273 (class 2606 OID 16457)
-- Name: Items FK_Items_Users; Type: FK CONSTRAINT; Schema: public; Owner: retrivo_db_user
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Users" FOREIGN KEY ("ReporterId") REFERENCES public."Users"("Id");


--
-- TOC entry 2072 (class 826 OID 16391)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO retrivo_db_user;


--
-- TOC entry 2074 (class 826 OID 16393)
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO retrivo_db_user;


--
-- TOC entry 2073 (class 826 OID 16392)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO retrivo_db_user;


--
-- TOC entry 2071 (class 826 OID 16390)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO retrivo_db_user;


-- Completed on 2026-07-27 19:52:35

--
-- PostgreSQL database dump complete
--

\unrestrict 10V82aseLUy9CsdceEd2YqtLbEioqFFHQ3OriqPsVUIbcOedwZzai1XkpoQZyvK

